export const ROUTES = {
    AUTH: 'auth',
    LOGIN: 'login',
    REGISTER: 'register',
    TASKS: 'tasks',
    ALL_TASKS: 'all-tasks',
    PENDING: 'pending',
    DONE: 'done',
    STATS: 'stats',
    TOGGLE: 'toggle',
    CHECK_AVAILABILITY: 'check-availability',
    FORGOT_PASSWORD: 'forgot-password',
    RESET_PASSWORD: 'reset-password',
    PROFILE: 'profile',
} as const